export default {
    COLOR_MORADO: '#702283',
    COLOR_LILA: '#962071',
    COLOR_VERDE: '#76B39D',
    
    COLOR_AMARILLO: '#FDB44B',
    COLOR_BLANCO: '#FFF',
    COLOR_AMARILLO_PASTEL: '#FBE7C6',
    COLOR_ROSA_PASTEL: '#F7CAC9',
}